### PR TITLE
more icons

### PR DESCRIPTION
**Pull request by after99**

### CODE REVIEW

**Comment by eikek** [comment]
I think there is a typo: `docshell` -> `docspell` :-) thanks

**Comment by after99** [comment]
fix

**Comment by after99** [comment]
hi @NX211

**Comment by NX211** [comment]
Hi @after99

**Comment by NX211** [comment]
This PR is rather large and contains many icons that aren't on par with the rest of the repo. I've tried not to use solid black icons as they don't do well with homers light and dark themes. Most of the icons in the repo also follow a minimum size requirement of around 500 pixels square. If I had the time I would pull out all of the icons that I could from this PR and merge them. I appreciate all of your hard work on this PR I just don't want to merge such a large number of icons if they're not being used.

**Comment by NX211** [comment]
I just saw eikek/docspell. I can see now why you're wanting to merge so many icons. I'll review your PR ASAP

**Pull request merged**
